version: 2

models:
  - name: fct_accidents
    description: "Core accident facts table with users, vehicles, and contextual data"
    columns:
      - name: accident_id
        description: "Unique accident identifier"
        tests:
          - not_null
      - name: user_id
        description: "Unique user identifier within accident"
      - name: vehicle_id
        description: "Unique vehicle identifier within accident"


  - name: fct_accidents_hr
    description: "Human-readable version of accident facts with descriptive labels"
    columns:
      - name: accident_id
        description: "Unique accident identifier"
        tests:
          - not_null
      - name: severity_label
        description: "Human-readable severity description"
      - name: gender_label
        description: "Human-readable gender description"
      - name: vehicle_category_label
        description: "Human-readable vehicle category"
      - name: trip_purpose_label
        description: "Human-readable trip purpose"

  - name: fct_accident_ml
    description: "ML-focused feature mart for bicycle accident analysis"
    columns:
      - name: accident_id
        description: "Unique accident identifier"
        tests:
          - not_null