version: 2

models:
  - name: fct_accidents
    description: "Core accident facts table with users, vehicles, and contextual data"
    columns:
      - name: accident_id
        description: "Unique accident identifier"
        tests:
          - not_null
      - name: user_id
        description: "Unique user identifier within accident"
        tests:
          - not_null
      - name: vehicle_id
        description: "Unique vehicle identifier within accident"
        tests:
          - not_null
      - name: is_severe_accident
        description: "Binary flag for severe accidents (fatal or hospitalized)"


  - name: fct_accidents_hr
    description: "Human-readable version of accident facts with descriptive labels"
    columns:
      - name: accident_id
        description: "Unique accident identifier"
        tests:
          - not_null
      - name: severity_label
        description: "Human-readable severity description"
      - name: gender_label
        description: "Human-readable gender description"
      - name: vehicle_category_label
        description: "Human-readable vehicle category"
      - name: trip_purpose_label
        description: "Human-readable trip purpose"

  - name: fct_accident_causes
    description: "ML-focused feature mart for bicycle accident analysis"
    columns:
      - name: accident_id
        description: "Unique accident identifier"
        tests:
          - not_null
      - name: is_severe_accident
        description: "Target variable for ML models"
        tests:
          - not_null
      - name: night_poor_visibility
        description: "Derived risk flag for night + poor visibility"
      - name: adverse_weather_surface
        description: "Derived risk flag for adverse weather + surface conditions"

  - name: fct_bike_accidents_idf
    description: "Bicycle accidents in Île-de-France region"
    columns:
      - name: accident_id
        description: "Unique accident identifier"
        tests:
          - not_null

  - name: fct_micromobility_accidents_idf
    description: "All micromobility vehicle accidents in Île-de-France region"
    columns:
      - name: accident_id
        description: "Unique accident identifier"
        tests:
          - not_null


  - name: fct_micromobility_visualization
    description: "Comprehensive visualization mart for micromobility accident analysis"
    columns:
      - name: accident_id
        description: "Unique accident identifier"
        tests:
          - not_null
      - name: user_id
        description: "Unique user identifier within accident"
        tests:
          - not_null