# The name that dbt_project.yml will use to refer to this project
safe_biking:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      # The credential file is mounted at /app/credentials.json in the container
      keyfile: /app/credentials.json
      project: biking-in-paris
      dataset: accidents 
      # Update the location if needed
      location: US
      threads: 6 
